import Testing
import Foundation
@testable import LearnrEngine

/// The vectors these run against were generated by running the real
/// `src/lib/figures/build.ts` under tsx — not by reimplementing it. See
/// `tools/generate-figure-vectors.ts`.
///
/// Coordinates are compared for **exact equality**, not within a tolerance.
/// `build.ts` rounds every one to `figurePrecision` places and normalises `-0`
/// to `0` on the way out, precisely so two figures that are the same drawing
/// are the same bytes — so a tolerance here would be throwing away the property
/// the rounding exists to provide.
struct FigureTests {
    struct Vector: Decodable {
        let name: String
        let seed: String
        let spec: FigureSpec
        let scope: [String: ScopeValue]
        let figure: Figure

        /// The bound variables, as the generator recorded them.
        var boundScope: Scope {
            scope.mapValues(\.value)
        }
    }

    enum ScopeValue: Decodable {
        case number(Double)
        case string(String)
        case boolean(Bool)

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let b = try? c.decode(Bool.self) { self = .boolean(b) }
            else if let n = try? c.decode(Double.self) { self = .number(n) }
            else { self = .string(try c.decode(String.self)) }
        }

        var value: Value {
            switch self {
            case .number(let n): return .number(n)
            case .string(let s): return .string(s)
            case .boolean(let b): return .boolean(b)
            }
        }
    }

    static let vectors: [Vector] = {
        let url = Bundle.module.url(forResource: "Vectors/figure-vectors", withExtension: "json")!
        return try! JSONDecoder().decode([Vector].self, from: Data(contentsOf: url))
    }()

    /// The kinds this port has builders for.
    ///
    /// Vectors for a kind not yet ported are skipped rather than failed: an
    /// absent kind falls back to the polygon builder, so running them would
    /// assert that a triangle is a clock face. The count is checked below so a
    /// kind cannot be quietly dropped from the sweep instead of being ported.
    static let portedKinds: Set<String> = ["polygon", "angle", "array", "spinner", "clock", "fraction-shape"]

    static var ported: [Vector] {
        vectors.filter { portedKinds.contains($0.spec.kind) }
    }

    @Test("buildFigure reproduces the TypeScript builders exactly")
    func matchesOracle() {
        let subject = Self.ported
        #expect(!subject.isEmpty)

        for vector in subject {
            var rng = Rng(seed: vector.seed)
            let actual = buildFigure(vector.spec, vector.boundScope, &rng)

            #expect(actual.width == vector.figure.width, "\(vector.name): width")
            #expect(actual.height == vector.figure.height, "\(vector.name): height")
            #expect(
                actual.marks.count == vector.figure.marks.count,
                "\(vector.name): mark count — \(actual.marks.count) vs \(vector.figure.marks.count)"
            )

            for (i, expected) in vector.figure.marks.enumerated() where i < actual.marks.count {
                #expect(actual.marks[i] == expected, "\(vector.name): mark \(i)")
            }
        }
    }

    @Test("a figure always comes back drawable, whatever the spec")
    func neverEmpty() {
        // `buildFigure` never throws and never gives back nothing: it runs
        // mid-session with a child waiting. The degradation vectors are the
        // ones that prove it, since shipped content cannot reach those paths.
        for vector in Self.ported where vector.name.hasPrefix("degrade.") {
            var rng = Rng(seed: vector.seed)
            #expect(!buildFigure(vector.spec, vector.boundScope, &rng).marks.isEmpty,
                    "\(vector.name) drew nothing")
        }
    }

    @Test("an unknown kind falls back to a polygon rather than failing")
    func unknownKind() {
        var rng = Rng(seed: "unknown")
        let figure = buildFigure(FigureSpec(kind: "not-a-kind"), [:], &rng)
        #expect(!figure.marks.isEmpty)
    }

    @Test("every coordinate lands inside the box")
    func insideTheBox() {
        for vector in Self.ported {
            var rng = Rng(seed: vector.seed)
            for mark in buildFigure(vector.spec, vector.boundScope, &rng).marks {
                let points: [Point]
                switch mark {
                case .path(let p, _, _, _): points = p
                case .arc(let at, _, _, _): points = [at]
                case .dot(let at): points = [at]
                case .label(let at, _): points = [at]
                }
                for p in points {
                    #expect(p.x >= 0 && p.x <= figureBox && p.y >= 0 && p.y <= figureBox,
                            "\(vector.name): (\(p.x), \(p.y)) outside the box")
                }
            }
        }
    }

    @Test("the same seed always draws the same figure")
    func deterministic() {
        let vector = Self.ported[0]
        var a = Rng(seed: vector.seed)
        var b = Rng(seed: vector.seed)
        #expect(buildFigure(vector.spec, vector.boundScope, &a)
                == buildFigure(vector.spec, vector.boundScope, &b))
    }
}
