import Testing
import Foundation
@testable import LearnrEngine

/// The vectors these run against were generated by running the real
/// `src/lib/templates/generate.ts` under tsx — not by reimplementing it. That
/// is what makes them an oracle rather than a second opinion. See
/// `tools/generate-vectors.ts`.
///
/// 378 figure-free shipped templates are covered, three draws each, plus 31
/// hand-written cases for the mechanisms the shipped content does not exercise
/// (`jitter` appears in no template at all today).
struct GenerateTests {
    /// The recorded shape of one `generate()` call.
    ///
    /// Decoded as raw JSON rather than into `GeneratedQuestion` so that the
    /// comparison is against what the TypeScript literally emitted, not against
    /// this port's own idea of the shape.
    struct Vector: Decodable {
        let name: String
        let seed: String
        let spec: QuestionSpec
        let question: RecordedQuestion
    }

    struct RecordedQuestion: Decodable {
        let prompt: String
        let answer: JSONValue
        let answerType: AnswerType
        let choices: [JSONValue]?
        let hint: String?
        let vars: [String: JSONValue]
    }

    /// A JSON scalar, compared against an `Answer` by rendered string.
    enum JSONValue: Decodable, Equatable {
        case number(Double)
        case string(String)
        case boolean(Bool)

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let b = try? c.decode(Bool.self) { self = .boolean(b) }
            else if let n = try? c.decode(Double.self) { self = .number(n) }
            else { self = .string(try c.decode(String.self)) }
        }

        var asAnswer: Answer {
            switch self {
            case .number(let n): return .number(n)
            case .string(let s): return .string(s)
            case .boolean(let b): return .boolean(b)
            }
        }
    }

    static let vectors: [Vector] = {
        let url = Bundle.module.url(forResource: "Vectors/generate-vectors", withExtension: "json")!
        return try! JSONDecoder().decode([Vector].self, from: Data(contentsOf: url))
    }()

    @Test("generate() reproduces the TypeScript engine exactly")
    func matchesOracle() throws {
        #expect(!Self.vectors.isEmpty)

        for vector in Self.vectors {
            var rng = Rng(seed: vector.seed)
            let actual: GeneratedQuestion
            do {
                actual = try generate(vector.spec, &rng, label: vector.name)
            } catch {
                Issue.record("\(vector.name): threw \(error)")
                continue
            }

            let expected = vector.question

            // The prompt is the text a child reads, so it is compared exactly —
            // including the `String(2.0) == "2"` rendering that a naive port
            // would turn into "2.0".
            #expect(actual.prompt == expected.prompt, "\(vector.name): prompt")
            #expect(actual.answerType == expected.answerType, "\(vector.name): answerType")
            #expect(actual.hint == expected.hint, "\(vector.name): hint")

            // Answers are compared by rendered string rather than by value:
            // that is what the play screen shows and what de-duplicates the
            // options, so it is the property that has to agree.
            #expect(
                actual.answer.stringValue == expected.answer.asAnswer.stringValue,
                "\(vector.name): answer — \(actual.answer) vs \(expected.answer)"
            )

            // Order matters: it is the Fisher-Yates shuffle's output, and a
            // port that shuffled differently would still contain the right set.
            let actualChoices = actual.choices?.map(\.stringValue)
            let expectedChoices = expected.choices?.map { $0.asAnswer.stringValue }
            #expect(actualChoices == expectedChoices, "\(vector.name): choices")

            let actualVars = actual.vars.mapValues(\.stringValue)
            let expectedVars = expected.vars.mapValues { $0.asAnswer.stringValue }
            #expect(actualVars == expectedVars, "\(vector.name): vars")
        }
    }

    @Test("every shipped figure-free template is covered, three draws each")
    func shippedCoverage() {
        let shipped = Self.vectors.filter { $0.name.hasPrefix("shipped:") }
        let templates = Set(shipped.map { $0.name.split(separator: "#")[0] })
        #expect(templates.count == 378)
        #expect(shipped.count == templates.count * 3)
    }

    @Test("the same seed always gives the same question")
    func deterministic() throws {
        let vector = Self.vectors[0]
        var a = Rng(seed: vector.seed)
        var b = Rng(seed: vector.seed)
        #expect(try generate(vector.spec, &a) == (try generate(vector.spec, &b)))
    }

    @Test("a template carrying a figure is refused, not silently stripped")
    func figureRefused() throws {
        let json = """
        {
          "prompt": "How many sides?",
          "vars": [{ "name": "n", "kind": "int", "min": "3", "max": "8" }],
          "answer": "n",
          "figure": { "kind": "polygon", "sides": "n" }
        }
        """
        let spec = try JSONDecoder().decode(QuestionSpec.self, from: Data(json.utf8))
        #expect(spec.hasFigure)

        var rng = Rng(seed: "fig")
        #expect(throws: GenerateError.figureUnsupported(label: "poly")) {
            try generate(spec, &rng, label: "poly")
        }
    }

    @Test("constraints that cannot be satisfied fail rather than loop")
    func impossibleConstraints() throws {
        let json = """
        {
          "prompt": "What is {x}?",
          "vars": [{ "name": "x", "kind": "int", "min": "1", "max": "10" }],
          "constraints": ["x > 100"],
          "answer": "x"
        }
        """
        let spec = try JSONDecoder().decode(QuestionSpec.self, from: Data(json.utf8))
        var rng = Rng(seed: "impossible")
        #expect(throws: GenerateError.self) {
            try generate(spec, &rng, label: "impossible")
        }
    }

    @Test("an empty range is reported against the variable that has it")
    func emptyRange() throws {
        let json = """
        {
          "prompt": "What is {x}?",
          "vars": [{ "name": "x", "kind": "int", "min": "10", "max": "1" }],
          "answer": "x"
        }
        """
        let spec = try JSONDecoder().decode(QuestionSpec.self, from: Data(json.utf8))
        var rng = Rng(seed: "empty")
        #expect(throws: GenerateError.emptyRange(name: "x", min: 10, max: 1)) {
            try generate(spec, &rng)
        }
    }

    @Test("a hole holding no expression is left as literal text")
    func literalBraces() throws {
        let scope: Scope = ["x": .number(3)]
        #expect(try renderTemplateString("a {} b", scope) == "a {} b")
        #expect(try renderTemplateString("{x} and {x}", scope) == "3 and 3")
        #expect(try renderTemplateString("no holes", scope) == "no holes")
    }

    @Test("a whole-number double renders the JavaScript way")
    func wholeNumberRendering() throws {
        let scope: Scope = ["x": .number(4)]
        // "2", not "2.0" — this text reaches a child in a prompt.
        #expect(try renderTemplateString("{x / 2}", scope) == "2")
    }
}
