import Testing
import Foundation
@testable import LearnrEngine

/// The vectors these run against were generated by running the real
/// `src/lib/rng.ts` under tsx - not by reimplementing it. That is what makes
/// them an oracle rather than a second opinion.
struct RngTests {
    struct Vectors: Decodable {
        struct Next: Decodable { let seed: String; let values: [Double] }
        struct Int_: Decodable { let seed: String; let min: Int; let max: Int; let values: [Int] }
        struct Pick: Decodable { let seed: String; let items: [String]; let values: [String] }
        let next: [Next]
        let int: [Int_]
        let pick: [Pick]
    }

    static let vectors: Vectors = {
        let url = Bundle.module.url(forResource: "Vectors/rng-vectors", withExtension: "json")!
        return try! JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }()

    @Test("next() reproduces the TypeScript engine exactly")
    func nextMatchesOracle() {
        for group in Self.vectors.next {
            var rng = Rng(seed: group.seed)
            for (i, expected) in group.values.enumerated() {
                let actual = rng.next()
                // Bit-exact, not approximate. Both sides compute the same
                // integer and divide by the same power of two, so any
                // difference at all is a real divergence.
                #expect(actual == expected,
                        "seed \(group.seed.debugDescription) draw \(i): \(actual) != \(expected)")
            }
        }
    }

    @Test("int() reproduces the TypeScript engine exactly")
    func intMatchesOracle() {
        for group in Self.vectors.int {
            var rng = Rng(seed: group.seed)
            for (i, expected) in group.values.enumerated() {
                let actual = rng.int(group.min, group.max)
                #expect(actual == expected,
                        "seed \(group.seed.debugDescription) [\(group.min),\(group.max)] draw \(i)")
            }
        }
    }

    @Test("pick() reproduces the TypeScript engine exactly")
    func pickMatchesOracle() {
        for group in Self.vectors.pick {
            var rng = Rng(seed: group.seed)
            for (i, expected) in group.values.enumerated() {
                #expect(rng.pick(group.items) == expected, "seed \(group.seed) draw \(i)")
            }
        }
    }

    @Test("the same seed always gives the same sequence")
    func deterministic() {
        var a = Rng(seed: "repeat")
        var b = Rng(seed: "repeat")
        for _ in 0..<50 { #expect(a.next() == b.next()) }
    }

    @Test("different seeds diverge")
    func seedsMatter() {
        var a = Rng(seed: "one")
        var b = Rng(seed: "two")
        #expect(a.next() != b.next())
    }

    @Test("int() stays inside its range, including a single-value range")
    func intBounds() {
        var rng = Rng(seed: "bounds")
        for _ in 0..<500 {
            let v = rng.int(-5, 5)
            #expect(v >= -5 && v <= 5)
        }
        var fixed = Rng(seed: "fixed")
        #expect(fixed.int(3, 3) == 3)
    }

    @Test("hashSeed matches FNV-1a offset basis for the empty string")
    func emptySeedHash() {
        #expect(Rng.hashSeed("") == 2166136261)
    }
}
