import Testing
import Foundation
@testable import LearnrEngine

/// The vectors these run against were generated by running the real
/// `src/lib/session/`, `src/lib/analytics/profile.ts`,
/// `src/lib/reinforcement/select.ts` and `src/lib/day.ts` under tsx — not by
/// reimplementing them. See `tools/generate-session-vectors.ts`.
struct SessionTests {

    // MARK: - Vector shapes

    struct Corpus: Decodable {
        let pool: [QuestionTemplate]
        let choiceTemplate: QuestionTemplate
        let booleanTemplate: QuestionTemplate
        let textTemplate: QuestionTemplate
        let day: [DayVector]
        let offsets: [OffsetVector]
        let profiles: [ProfileVector]
        let steps: [StepVector]
        let select: [SelectVector]
        let grade: [GradeVector]
        let answers: [AnswerVector]
        let keypad: [KeypadVector]
        let sessions: [SessionVector]
        let durations: [DurationVector]
        let constants: Constants
    }

    struct DayVector: Decodable {
        let name: String
        let at: Int
        let offsetMinutes: Int?
        let day: Int
    }

    struct OffsetVector: Decodable {
        let name: String
        /// Null for the `null` case, which is one of the non-number inputs the
        /// TypeScript's `typeof` guard refuses.
        let value: JSONScalar?
        let parsed: Int?
    }

    struct RecordedObservation: Decodable {
        let topic: String
        let level: String
        let correct: Bool
        let timeTakenMs: Int
        let answeredAt: Int
        let offsetMinutes: Int?

        var observation: Observation {
            Observation(
                topic: topic, level: level, correct: correct,
                timeTakenMs: timeTakenMs, answeredAt: answeredAt,
                offsetMinutes: offsetMinutes ?? 0)
        }
    }

    /// A skill row as the TypeScript emitted it. Decoded separately from
    /// `SkillRow` so the comparison is against what the oracle wrote, not
    /// against this port's idea of the shape.
    struct RecordedSkill: Decodable, Equatable {
        let topic: String
        let level: String
        let attempts: Int
        let correct: Int
        let strength: Double
        let streak: Int
        let correctDays: Int
        let lastCorrectDay: Int?
        let totalTimeMs: Int
        let lastAnsweredAt: Int
    }

    struct RecordedProfile: Decodable {
        let skills: [RecordedSkill]
    }

    struct ProfileVector: Decodable {
        let name: String
        let observations: [RecordedObservation]
        let profile: RecordedProfile
        let hasPattern: Bool
        let statuses: [StatusReading]
        let derived: [DerivedReading]
        let recentTopics: [String]
    }

    struct StatusReading: Decodable {
        let now: Int
        let skills: [StatusEntry]
    }

    struct StatusEntry: Decodable {
        let topic: String
        let level: String
        let status: String
    }

    struct DerivedReading: Decodable {
        let topic: String
        let level: String
        let accuracy: Double
        let averageTimeMs: Int
        let reviewIntervalMs: Int
        let reviewDueAt: Int
    }

    struct StepVector: Decodable {
        let name: String
        let previous: RecordedSkill?
        let observation: RecordedObservation
        let next: RecordedSkill
    }

    struct SelectVector: Decodable {
        let name: String
        let templateIds: [String]
        let profile: RecordedProfile
        let now: Int
        let recent: [String]
        let weighted: [WeightEntry]
        let focusTopics: [String]
        let draws: [DrawEntry]
    }

    struct WeightEntry: Decodable {
        let id: String
        let topic: String
        let status: String
        let weight: Double
    }

    struct DrawEntry: Decodable {
        let seed: String
        let id: String
        let nextAfter: Double
    }

    struct GradeVector: Decodable {
        let name: String
        let question: RecordedQuestion
        let response: String
        let grade: RecordedGrade
    }

    struct RecordedGrade: Decodable {
        let correct: Bool
        let response: String
    }

    /// The question shape the grade and answer vectors carry — a bare question,
    /// not a generated one, so it is rebuilt into a `GeneratedQuestion` here.
    struct RecordedQuestion: Decodable {
        let prompt: String
        let answer: JSONScalar
        let answerType: AnswerType?
        let choices: [JSONScalar]?

        var generated: GeneratedQuestion {
            GeneratedQuestion(
                prompt: prompt,
                answer: answer.asAnswer,
                // `generate` always resolves a type; these vectors record the
                // spec's declared one, which may be absent. The fallback
                // mirrors what `gradeAnswer` infers from the answer itself.
                answerType: answerType ?? answer.inferredType,
                choices: choices?.map(\.asAnswer),
                hint: nil,
                vars: [:],
                figure: nil)
        }
    }

    struct AnswerVector: Decodable {
        let name: String
        let question: RecordedQuestion
        let mode: String
        let options: [RecordedOption]
        let formatted: String
    }

    struct RecordedOption: Decodable, Equatable {
        let value: String
        let label: String
    }

    struct KeypadVector: Decodable {
        let name: String
        let entry: String
        let key: String
        let result: String
    }

    struct SessionVector: Decodable {
        let name: String
        let templateIds: [String]
        let seed: String
        let startedAt: Int
        let subject: String?
        let level: String?
        let profile: RecordedProfile?
        let recentTopics: [String]?
        let opening: RecordedState
        let steps: [RecordedStep]
    }

    struct RecordedStep: Decodable {
        let response: String
        let now: Int
        let offsetMinutes: Int
        let state: RecordedState
    }

    struct RecordedState: Decodable {
        let subject: String
        let level: String
        let startedAt: Int
        let questionShownAt: Int
        let askedCount: Int
        let draw: Int
        let seed: String
        let current: RecordedCurrent
        let attempts: [RecordedAttempt]
        let profile: RecordedProfile
        let recentTopics: [String]
        let elapsedMs: Int
        let formattedDuration: String
    }

    struct RecordedCurrent: Decodable {
        let templateId: String
        let subject: String
        let topic: String
        let level: String
        let prompt: String
        let answer: JSONScalar
        let answerType: AnswerType
        let choices: [JSONScalar]?
        let figure: Figure?
    }

    struct RecordedAttempt: Decodable {
        let templateId: String
        let subject: String
        let topic: String
        let level: String
        let prompt: String
        let expected: String
        let response: String
        let correct: Bool
        let timeTakenMs: Int
        let answeredAt: Int
        let offsetMinutes: Int
        let figure: Figure?
    }

    struct DurationVector: Decodable {
        let ms: Int
        let formatted: String
    }

    struct Constants: Decodable {
        let RECENCY: Double
        let MIN_OBSERVATIONS: Int
        let STRUGGLING_BELOW: Double
        let SECURE_AT: Double
        let SECURE_STREAK: Int
        let SECURE_OBSERVATIONS: Int
        let SECURE_DAYS: Int
        let REVIEW_INTERVALS_MS: [Int]
        let STATUS_WEIGHTS: [String: Double]
        let MIN_FOCUS_SHARE: Double
        let MAX_FOCUS_SHARE: Double
        let COOLDOWN: [Double]
        let RECENT_MEMORY: Int
        let MAX_TIME_MS: Int
        let MAX_NUMBER_LENGTH: Int
        let BOOLEAN_OPTIONS: [RecordedOption]
    }

    /// A JSON scalar, as recorded.
    enum JSONScalar: Decodable, Equatable {
        case number(Double)
        case string(String)
        case boolean(Bool)

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let b = try? c.decode(Bool.self) { self = .boolean(b) }
            else if let n = try? c.decode(Double.self) { self = .number(n) }
            else { self = .string(try c.decode(String.self)) }
        }

        var asAnswer: Answer {
            switch self {
            case .number(let n): return .number(n)
            case .string(let s): return .string(s)
            case .boolean(let b): return .boolean(b)
            }
        }

        var inferredType: AnswerType {
            switch self {
            case .number: return .number
            case .string: return .text
            case .boolean: return .boolean
            }
        }
    }

    static let corpus: Corpus = {
        let url = Bundle.module.url(forResource: "Vectors/session-vectors", withExtension: "json")!
        return try! JSONDecoder().decode(Corpus.self, from: Data(contentsOf: url))
    }()

    /// Compares a Swift skill row against the recorded one.
    ///
    /// `strength` is compared exactly rather than within a tolerance. It is a
    /// chain of `previous + 0.4 * (outcome - previous)` in IEEE doubles, and
    /// both engines do the same operations in the same order — so it either
    /// agrees bit for bit or the fold has diverged, and a tolerance would hide
    /// exactly the drift these vectors exist to catch.
    static func check(_ actual: SkillRow, _ expected: RecordedSkill, _ label: String) {
        #expect(actual.topic == expected.topic, "\(label): topic")
        #expect(actual.level == expected.level, "\(label): level")
        #expect(actual.attempts == expected.attempts, "\(label): attempts")
        #expect(actual.correct == expected.correct, "\(label): correct")
        #expect(actual.strength == expected.strength,
                "\(label): strength — \(actual.strength) vs \(expected.strength)")
        #expect(actual.streak == expected.streak, "\(label): streak")
        #expect(actual.correctDays == expected.correctDays, "\(label): correctDays")
        #expect(actual.lastCorrectDay == expected.lastCorrectDay, "\(label): lastCorrectDay")
        #expect(actual.totalTimeMs == expected.totalTimeMs, "\(label): totalTimeMs")
        #expect(actual.lastAnsweredAt == expected.lastAnsweredAt, "\(label): lastAnsweredAt")
    }

    static func skillRow(_ recorded: RecordedSkill) -> SkillRow {
        SkillRow(
            topic: recorded.topic, level: recorded.level, attempts: recorded.attempts,
            correct: recorded.correct, strength: recorded.strength, streak: recorded.streak,
            correctDays: recorded.correctDays, lastCorrectDay: recorded.lastCorrectDay,
            totalTimeMs: recorded.totalTimeMs, lastAnsweredAt: recorded.lastAnsweredAt)
    }

    static func profileState(_ recorded: RecordedProfile) -> LearnerProfileState {
        LearnerProfileState(skills: recorded.skills.map(skillRow))
    }

    // MARK: - Day

    @Test("localDay reproduces the TypeScript, negatives included")
    func dayMatchesOracle() {
        #expect(!Self.corpus.day.isEmpty)
        for vector in Self.corpus.day {
            let actual = vector.offsetMinutes == nil
                ? Day.localDay(vector.at)
                : Day.localDay(vector.at, vector.offsetMinutes!)
            #expect(actual == vector.day, "\(vector.name): \(actual) vs \(vector.day)")
        }
    }

    @Test("parseOffsetMinutes refuses what would poison a stored day")
    func offsetsMatchOracle() {
        for vector in Self.corpus.offsets {
            // Only a number can be an offset; the non-numeric cases are what
            // the `typeof value !== 'number'` guard refuses, and Swift's type
            // system refuses them at the call site instead.
            guard case .number(let value) = vector.value ?? .string("null") else {
                #expect(vector.parsed == nil, "\(vector.name): a non-number must not parse")
                continue
            }
            #expect(Day.parseOffsetMinutes(value) == vector.parsed, "\(vector.name)")
        }
    }

    // MARK: - Profile

    @Test("buildProfile folds exactly as the TypeScript does")
    func profileMatchesOracle() {
        #expect(!Self.corpus.profiles.isEmpty)

        for vector in Self.corpus.profiles {
            let actual = Profile.buildProfile(vector.observations.map(\.observation))

            #expect(actual.skills.count == vector.profile.skills.count,
                    "\(vector.name): skill count")
            guard actual.skills.count == vector.profile.skills.count else { continue }

            // Compared pairwise in order: `applyObservation` appends a new skill
            // at the end, so the order is part of the value and a port using a
            // dictionary would pass a set comparison while producing an
            // unstable profile.
            for (actualSkill, expectedSkill) in zip(actual.skills, vector.profile.skills) {
                Self.check(actualSkill, expectedSkill, "\(vector.name)/\(expectedSkill.topic)")
            }

            #expect(Profile.hasPattern(actual) == vector.hasPattern, "\(vector.name): hasPattern")
            #expect(Profile.recentTopics(vector.observations.map(\.observation), 3)
                == vector.recentTopics, "\(vector.name): recentTopics")
        }
    }

    @Test("skillStatus agrees at every clock, including the review boundary")
    func statusMatchesOracle() {
        for vector in Self.corpus.profiles {
            let actual = Profile.buildProfile(vector.observations.map(\.observation))

            for reading in vector.statuses {
                for entry in reading.skills {
                    let skill = Profile.findSkill(actual, entry.topic, entry.level)
                    let status = Profile.skillStatus(skill, reading.now)
                    let where_ = "\(vector.name)/\(entry.topic)@\(reading.now)"
                    #expect(status.rawValue == entry.status,
                            "\(where_): \(status.rawValue) vs \(entry.status)")
                }
            }
        }
    }

    @Test("the derived read-outs agree too")
    func derivedMatchesOracle() {
        for vector in Self.corpus.profiles {
            let actual = Profile.buildProfile(vector.observations.map(\.observation))

            for reading in vector.derived {
                guard let skill = Profile.findSkill(actual, reading.topic, reading.level) else {
                    Issue.record("\(vector.name): missing skill \(reading.topic)")
                    continue
                }
                let label = "\(vector.name)/\(reading.topic)"
                #expect(Profile.accuracy(skill) == reading.accuracy, "\(label): accuracy")
                #expect(Profile.averageTimeMs(skill) == reading.averageTimeMs,
                        "\(label): averageTimeMs")
                #expect(Profile.reviewIntervalMs(skill) == reading.reviewIntervalMs,
                        "\(label): reviewIntervalMs")
                #expect(Profile.reviewDueAt(skill) == reading.reviewDueAt, "\(label): reviewDueAt")
            }
        }
    }

    @Test("nextSkill folds one answer exactly")
    func stepMatchesOracle() {
        #expect(!Self.corpus.steps.isEmpty)
        for vector in Self.corpus.steps {
            let previous = vector.previous.map(Self.skillRow)
            let actual = Profile.nextSkill(previous, vector.observation.observation)
            Self.check(actual, vector.next, vector.name)
        }
    }

    // MARK: - Selector

    @Test("weightTemplates reproduces the policy, weight for weight")
    func weightsMatchOracle() {
        #expect(!Self.corpus.select.isEmpty)

        for vector in Self.corpus.select {
            let templates = Self.templates(for: vector.templateIds)
            let context = Select.Context(
                profile: Self.profileState(vector.profile),
                now: vector.now,
                recent: vector.recent)

            let actual = Select.weightTemplates(templates, context)
            #expect(actual.count == vector.weighted.count, "\(vector.name): count")
            guard actual.count == vector.weighted.count else { continue }

            for (entry, expected) in zip(actual, vector.weighted) {
                let label = "\(vector.name)/\(expected.id)"
                #expect(entry.template.id == expected.id, "\(label): order")
                #expect(entry.status.rawValue == expected.status, "\(label): status")
                // Exact, for the same reason `strength` is: this is a product of
                // a quotient and a table lookup, and both engines do it in the
                // same order.
                #expect(entry.weight == expected.weight,
                        "\(label): weight — \(entry.weight) vs \(expected.weight)")
            }

            #expect(Select.focusTopics(templates, context) == vector.focusTopics,
                    "\(vector.name): focusTopics")
        }
    }

    @Test("selectTemplate draws the same template and spends the same draws")
    func drawsMatchOracle() throws {
        for vector in Self.corpus.select {
            let templates = Self.templates(for: vector.templateIds)
            let context = Select.Context(
                profile: Self.profileState(vector.profile),
                now: vector.now,
                recent: vector.recent)

            for draw in vector.draws {
                var rng = Rng(seed: draw.seed)
                let picked = try Select.selectTemplate(templates, context, &rng)
                #expect(picked.id == draw.id, "\(vector.name)@\(draw.seed): picked")
                // The rng's next value, which catches a port that picks the
                // right template while spending a different number of draws.
                #expect(rng.next() == draw.nextAfter, "\(vector.name)@\(draw.seed): draws spent")
            }
        }
    }

    @Test("an empty pool is refused rather than returning nothing")
    func emptyPoolRefused() {
        var rng = Rng(seed: "x")
        #expect(throws: SelectError.emptyPool) {
            try Select.selectTemplate([], Select.Context(profile: .empty, now: 0), &rng)
        }
    }

    // MARK: - Grading

    @Test("gradeAnswer reproduces the TypeScript, JS coercions included")
    func gradeMatchesOracle() {
        #expect(!Self.corpus.grade.isEmpty)
        for vector in Self.corpus.grade {
            let actual = Grading.gradeAnswer(vector.question.generated, vector.response)
            #expect(actual.correct == vector.grade.correct,
                    "\(vector.name): correct — \(actual.correct) vs \(vector.grade.correct)")
            #expect(actual.response == vector.grade.response, "\(vector.name): response")
        }
    }

    @Test("the empty response is never correct, even against zero")
    func emptyIsNeverCorrect() {
        // `Number('')` is 0, so without the explicit guard in `gradeAnswer` a
        // child who submits nothing is marked right on every zero-answer
        // question. Pinned here as well as in the vectors because it is the one
        // coercion that silently rewards not answering.
        let zero = GeneratedQuestion(
            prompt: "p", answer: .number(0), answerType: .number,
            choices: nil, hint: nil, vars: [:], figure: nil)
        #expect(Grading.gradeAnswer(zero, "").correct == false)
        #expect(Grading.gradeAnswer(zero, "   ").correct == false)
        #expect(Grading.gradeAnswer(zero, "0").correct == true)
    }

    // MARK: - Answer presentation

    @Test("answerMode, answerOptions and formatAnswer agree")
    func answersMatchOracle() {
        #expect(!Self.corpus.answers.isEmpty)
        for vector in Self.corpus.answers {
            let question = vector.question.generated
            #expect(Answers.answerMode(question).rawValue == vector.mode, "\(vector.name): mode")
            let options = Answers.answerOptions(question).map {
                RecordedOption(value: $0.value, label: $0.label)
            }
            #expect(options == vector.options, "\(vector.name): options")
            #expect(Answers.formatAnswer(question) == vector.formatted,
                    "\(vector.name): formatted")
        }
    }

    @Test("appendNumeric applies the keypad rules")
    func keypadMatchesOracle() {
        #expect(!Self.corpus.keypad.isEmpty)
        for vector in Self.corpus.keypad {
            #expect(Answers.appendNumeric(vector.entry, vector.key) == vector.result,
                    "\(vector.name)")
        }
    }

    // MARK: - The state machine

    static func templates(for ids: [String]) -> [QuestionTemplate] {
        let all = corpus.pool + [corpus.choiceTemplate, corpus.booleanTemplate, corpus.textTemplate]
        return ids.compactMap { id in all.first { $0.id == id } }
    }

    @Test("a whole session replays exactly, question for question")
    func sessionMatchesOracle() throws {
        #expect(!Self.corpus.sessions.isEmpty)

        for vector in Self.corpus.sessions {
            let templates = Self.templates(for: vector.templateIds)
            #expect(templates.count == vector.templateIds.count, "\(vector.name): pool resolved")

            var state = try Sessions.startSession(SessionConfig(
                templates: templates,
                seed: vector.seed,
                startedAt: vector.startedAt,
                subject: vector.subject,
                level: vector.level,
                profile: vector.profile.map(Self.profileState),
                recentTopics: vector.recentTopics))

            Self.check(state, vector.opening, vector.startedAt, "\(vector.name)/opening")

            for (index, step) in vector.steps.enumerated() {
                state = try Sessions.submitAnswer(
                    state, step.response, step.now, step.offsetMinutes)
                Self.check(state, step.state, step.now, "\(vector.name)/step\(index)")
            }
        }
    }

    /// Compares a session state against the recorded one, field by field.
    static func check(
        _ actual: SessionState, _ expected: RecordedState, _ now: Int, _ label: String
    ) {
        #expect(actual.subject == expected.subject, "\(label): subject")
        #expect(actual.level == expected.level, "\(label): level")
        #expect(actual.startedAt == expected.startedAt, "\(label): startedAt")
        #expect(actual.questionShownAt == expected.questionShownAt, "\(label): questionShownAt")
        #expect(actual.askedCount == expected.askedCount, "\(label): askedCount")
        #expect(actual.draw == expected.draw, "\(label): draw")
        #expect(actual.seed == expected.seed, "\(label): seed")
        #expect(actual.recentTopics == expected.recentTopics, "\(label): recentTopics")
        #expect(Sessions.elapsedMs(actual, now) == expected.elapsedMs, "\(label): elapsedMs")
        #expect(Sessions.formatDuration(Sessions.elapsedMs(actual, now))
            == expected.formattedDuration, "\(label): formattedDuration")

        // The question on screen. This is the selector, the RNG sequence and
        // generation all at once: a divergence in any of them shows up as a
        // different template or a different prompt.
        let drew = "\(actual.current.templateId) vs \(expected.current.templateId)"
        #expect(actual.current.templateId == expected.current.templateId,
                "\(label): current template — \(drew)")
        #expect(actual.current.topic == expected.current.topic, "\(label): current topic")
        #expect(actual.current.question.prompt == expected.current.prompt, "\(label): prompt")
        #expect(actual.current.question.answer.stringValue
            == expected.current.answer.asAnswer.stringValue, "\(label): answer")
        #expect(actual.current.question.answerType == expected.current.answerType,
                "\(label): answerType")
        #expect(actual.current.question.choices?.map(\.stringValue)
            == expected.current.choices?.map { $0.asAnswer.stringValue }, "\(label): choices")
        #expect(actual.current.question.figure == expected.current.figure, "\(label): figure")

        #expect(actual.attempts.count == expected.attempts.count, "\(label): attempt count")
        for (attempt, recorded) in zip(actual.attempts, expected.attempts) {
            let attemptLabel = "\(label)/attempt\(recorded.answeredAt)"
            #expect(attempt.templateId == recorded.templateId, "\(attemptLabel): templateId")
            #expect(attempt.subject == recorded.subject, "\(attemptLabel): subject")
            #expect(attempt.topic == recorded.topic, "\(attemptLabel): topic")
            #expect(attempt.level == recorded.level, "\(attemptLabel): level")
            #expect(attempt.prompt == recorded.prompt, "\(attemptLabel): prompt")
            #expect(attempt.expected == recorded.expected, "\(attemptLabel): expected")
            #expect(attempt.response == recorded.response, "\(attemptLabel): response")
            #expect(attempt.correct == recorded.correct, "\(attemptLabel): correct")
            #expect(attempt.timeTakenMs == recorded.timeTakenMs, "\(attemptLabel): timeTakenMs")
            #expect(attempt.answeredAt == recorded.answeredAt, "\(attemptLabel): answeredAt")
            #expect(attempt.offsetMinutes == recorded.offsetMinutes,
                    "\(attemptLabel): offsetMinutes")
            #expect(attempt.figure == recorded.figure, "\(attemptLabel): figure")
        }

        #expect(actual.profile.skills.count == expected.profile.skills.count,
                "\(label): profile size")
        for (skill, recorded) in zip(actual.profile.skills, expected.profile.skills) {
            check(skill, recorded, "\(label)/profile/\(recorded.topic)")
        }
    }

    @Test("an empty pool cannot start a session")
    func noTemplatesRefused() {
        #expect(throws: SessionError.noTemplates) {
            try Sessions.startSession(SessionConfig(templates: [], seed: "s", startedAt: 0))
        }
    }

    @Test("formatDuration counts up with no cap")
    func durationMatchesOracle() {
        for vector in Self.corpus.durations {
            #expect(Sessions.formatDuration(vector.ms) == vector.formatted, "\(vector.ms)")
        }
    }

    @Test("the same seed and profile always give the same session")
    func deterministic() throws {
        let config = SessionConfig(
            templates: Self.corpus.pool, seed: "repeat", startedAt: 1000)
        let a = try Sessions.startSession(config)
        let b = try Sessions.startSession(config)
        #expect(a.current.templateId == b.current.templateId)
        #expect(a.current.question == b.current.question)
    }

    // MARK: - Constants

    @Test("the ported constants match the TypeScript")
    func constantsMatchOracle() {
        let c = Self.corpus.constants
        #expect(Profile.recency == c.RECENCY)
        #expect(Profile.minObservations == c.MIN_OBSERVATIONS)
        #expect(Profile.strugglingBelow == c.STRUGGLING_BELOW)
        #expect(Profile.secureAt == c.SECURE_AT)
        #expect(Profile.secureStreak == c.SECURE_STREAK)
        #expect(Profile.secureObservations == c.SECURE_OBSERVATIONS)
        #expect(Profile.secureDays == c.SECURE_DAYS)
        #expect(Profile.reviewIntervalsMs == c.REVIEW_INTERVALS_MS)
        #expect(Select.minFocusShare == c.MIN_FOCUS_SHARE)
        #expect(Select.maxFocusShare == c.MAX_FOCUS_SHARE)
        #expect(Select.cooldown == c.COOLDOWN)
        #expect(Select.recentMemory == c.RECENT_MEMORY)
        #expect(Sessions.maxTimeMs == c.MAX_TIME_MS)
        #expect(Answers.maxNumberLength == c.MAX_NUMBER_LENGTH)
        #expect(Answers.booleanOptions.map { RecordedOption(value: $0.value, label: $0.label) }
            == c.BOOLEAN_OPTIONS)

        // Every status weight, by name, so a renamed or retuned status is caught
        // rather than silently defaulting.
        for status in SkillStatus.allCases {
            guard let expected = c.STATUS_WEIGHTS[status.rawValue] else {
                Issue.record("no recorded weight for \(status.rawValue)")
                continue
            }
            #expect(Select.statusWeight(status) == expected, "weight for \(status.rawValue)")
        }
    }
}
