import Testing
import Foundation
@testable import LearnrEngine

/// The vectors these run against were generated by running the real
/// `src/lib/speedrun/{run,modes,records}.ts` under tsx — not by reimplementing
/// them. See `tools/generate-speedrun-vectors.ts`.
struct SpeedRunTests {

    struct Corpus: Decodable {
        let modes: [ModeVector]
        let parse: [ParseVector]
        let operations: [OperationVector]
        let modesFor: [ModesForVector]
        let runs: [RunVector]
        let judge: [JudgeVector]
        let clock: [ClockVector]
        let pulses: [PulseVector]
        let records: [RecordVector]
        let constants: Constants
    }

    /// A mode as the TypeScript spells it: an object with an `op` and then
    /// either a `difficulty` or `tables`.
    struct RecordedMode: Decodable {
        let op: String
        let difficulty: String?
        let tables: JSONScalar?

        var mode: Mode? {
            guard let op = Operation(rawValue: op) else { return nil }
            if op == .multiply {
                guard let tables else { return nil }
                switch tables {
                case .number(let n): return .multiply(.single(Int(n)))
                case .string("2-5"): return .multiply(.bundle2to5)
                case .string("6-9"): return .multiply(.bundle6to9)
                case .string("11-12"): return .multiply(.bundle11to12)
                case .string("all"): return .multiply(.all)
                default: return nil
                }
            }
            guard let difficulty, let parsed = Difficulty(rawValue: difficulty) else { return nil }
            return .graded(op, parsed)
        }
    }

    struct ModeVector: Decodable {
        let mode: RecordedMode
        let key: String
        let specs: [QuestionSpec]
        let label: String
        let hardness: Double
        let isSingleTable: Bool
        let operationLabel: String
        let operationNoun: String
        let operationGlyph: String
    }

    struct ParseVector: Decodable {
        let key: String
        let mode: RecordedMode?
    }

    struct OperationVector: Decodable {
        let op: String
        let parsed: String?
    }

    struct ModesForVector: Decodable {
        let op: String
        let keys: [String]
    }

    struct RecordedQuestion: Decodable {
        let prompt: String
        let answer: JSONScalar
        let answerType: AnswerType
        let choices: [JSONScalar]?
    }

    struct RecordedRunState: Decodable {
        let draw: Int
        let correct: Int
        let current: RecordedQuestion
        let next: RecordedQuestion
    }

    struct RunStep: Decodable {
        let response: String
        let now: Int
        let verdict: String
        let advanced: Bool
        let state: RecordedRunState
    }

    struct RunVector: Decodable {
        let name: String
        let mode: RecordedMode
        let seed: String
        let startedAt: Int
        let opening: RecordedRunState
        let steps: [RunStep]
        let result: RecordedResult
    }

    struct RecordedResult: Decodable {
        let mode: RecordedMode
        let correct: Int
    }

    struct JudgeVector: Decodable {
        let name: String
        let mode: RecordedMode
        let seed: String
        let answer: String
        let entries: [JudgeEntry]
    }

    struct JudgeEntry: Decodable {
        let entry: String
        let verdict: String
    }

    struct ClockVector: Decodable {
        let elapsed: Int
        let now: Int
        let remaining: Int
        let isOver: Bool
        let pulse: String
    }

    struct PulseVector: Decodable {
        let remaining: Int
        let pulse: String
    }

    struct RecordVector: Decodable {
        let previousBest: Int?
        let score: Int
        let isRecord: Bool
        let tone: String
    }

    struct Constants: Decodable {
        let SPEED_RUN_MS: Int
        let COUNTDOWN_MS: Int
        let SPEED_RUN_SUBJECT: String
        let DIFFICULTIES: [String]
        let OPERATIONS: [String]
        let TABLES: [Int]
        let SINGLE_TABLES: [Int]
        let TABLE_BUNDLES: [String]
        let MODE_COUNT: Int
    }

    enum JSONScalar: Decodable, Equatable {
        case number(Double)
        case string(String)
        case boolean(Bool)

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let b = try? c.decode(Bool.self) { self = .boolean(b) }
            else if let n = try? c.decode(Double.self) { self = .number(n) }
            else { self = .string(try c.decode(String.self)) }
        }

        var asAnswer: Answer {
            switch self {
            case .number(let n): return .number(n)
            case .string(let s): return .string(s)
            case .boolean(let b): return .boolean(b)
            }
        }
    }

    static let corpus: Corpus = {
        let url = Bundle.module.url(forResource: "Vectors/speedrun-vectors", withExtension: "json")!
        return try! JSONDecoder().decode(Corpus.self, from: Data(contentsOf: url))
    }()

    // MARK: - Modes

    @Test("all twenty-six modes are enumerated, in order")
    func modesMatchOracle() {
        #expect(Modes.all.count == Self.corpus.constants.MODE_COUNT)
        #expect(Modes.all.map(\.key) == Self.corpus.modes.map(\.key))
    }

    @Test("every mode's label, hardness and glyphs agree")
    func modeReadoutsMatchOracle() throws {
        for vector in Self.corpus.modes {
            guard let mode = vector.mode.mode else {
                Issue.record("\(vector.key): could not rebuild the mode")
                continue
            }
            #expect(mode.key == vector.key, "\(vector.key): key")
            #expect(Modes.modeLabel(mode) == vector.label, "\(vector.key): label")
            #expect(Modes.modeHardness(mode) == vector.hardness, "\(vector.key): hardness")
            #expect(Modes.isSingleTable(mode) == vector.isSingleTable,
                    "\(vector.key): isSingleTable")
            #expect(Modes.operationLabel(mode.op) == vector.operationLabel,
                    "\(vector.key): operationLabel")
            #expect(Modes.operationNoun(mode.op) == vector.operationNoun,
                    "\(vector.key): operationNoun")
            #expect(Modes.operationGlyph(mode.op) == vector.operationGlyph,
                    "\(vector.key): operationGlyph")
        }
    }

    /// The shipped specs are the TypeScript's own literals, so this checks the
    /// *mapping* — that each mode reaches the specs `specsFor` gave it, and that
    /// a mixed mode reaches four of them in the right order.
    @Test("each mode maps to the specs the TypeScript gave it")
    func specsMatchOracle() throws {
        for vector in Self.corpus.modes {
            guard let mode = vector.mode.mode else { continue }
            let actual = try SpeedRun.specsFor(mode)
            #expect(actual.count == vector.specs.count, "\(vector.key): spec count")
            for (spec, expected) in zip(actual, vector.specs) {
                #expect(spec.prompt == expected.prompt, "\(vector.key): prompt")
                #expect(spec.answer == expected.answer, "\(vector.key): answer")
                #expect(spec.constraints == expected.constraints, "\(vector.key): constraints")
                #expect(spec.vars.count == expected.vars.count, "\(vector.key): var count")
            }
        }
    }

    @Test("parseMode accepts the real keys and refuses everything else")
    func parseMatchesOracle() {
        #expect(!Self.corpus.parse.isEmpty)
        for vector in Self.corpus.parse {
            let actual = Modes.parseMode(vector.key)
            #expect(actual?.key == vector.mode?.mode?.key,
                    "\(vector.key): \(actual?.key ?? "nil") vs \(vector.mode?.mode?.key ?? "nil")")
        }
    }

    @Test("the retired multiply.10 keys stay retired")
    func retiredKeysRefused() {
        // Both were real modes once, and a banked record under either simply
        // stops appearing rather than resurrecting the mode.
        #expect(Modes.parseMode("multiply.10") == nil)
        #expect(Modes.parseMode("multiply.10-12") == nil)
        // And a key is a dictionary lookup, never a property access.
        #expect(Modes.parseMode("__proto__") == nil)
        #expect(Modes.parseMode("constructor") == nil)
    }

    @Test("parseOperation and modesFor agree")
    func operationsMatchOracle() {
        for vector in Self.corpus.operations {
            #expect(Modes.parseOperation(vector.op)?.rawValue == vector.parsed, "\(vector.op)")
        }
        for vector in Self.corpus.modesFor {
            guard let op = Operation(rawValue: vector.op) else {
                Issue.record("\(vector.op): not an operation")
                continue
            }
            #expect(Modes.modesFor(op).map(\.key) == vector.keys, "\(vector.op)")
        }
    }

    // MARK: - Runs

    static func check(
        _ actual: GeneratedQuestion, _ expected: RecordedQuestion, _ label: String
    ) {
        #expect(actual.prompt == expected.prompt, "\(label): prompt")
        let got = "\(actual.answer.stringValue) vs \(expected.answer.asAnswer.stringValue)"
        #expect(actual.answer.stringValue == expected.answer.asAnswer.stringValue,
                "\(label): answer — \(got)")
        #expect(actual.answerType == expected.answerType, "\(label): answerType")
    }

    static func check(_ actual: RunState, _ expected: RecordedRunState, _ label: String) {
        #expect(actual.draw == expected.draw, "\(label): draw")
        #expect(actual.correct == expected.correct, "\(label): correct")
        check(actual.current, expected.current, "\(label)/current")
        // The lookahead, which the screen shows dimmed above. A run that
        // advanced correctly but drew this wrongly looks right until the next
        // answer arrives.
        check(actual.next, expected.next, "\(label)/next")
    }

    @Test("a whole run replays exactly, both slots at every step")
    func runsMatchOracle() throws {
        #expect(!Self.corpus.runs.isEmpty)

        for vector in Self.corpus.runs {
            guard let mode = vector.mode.mode else {
                Issue.record("\(vector.name): could not rebuild the mode")
                continue
            }

            var state = try SpeedRun.startRun(
                mode: mode, seed: vector.seed, startedAt: vector.startedAt)
            Self.check(state, vector.opening, "\(vector.name)/opening")

            for (index, step) in vector.steps.enumerated() {
                let label = "\(vector.name)/step\(index)"
                // The verdict is read before the transition, against the
                // question then on screen.
                #expect(SpeedRun.judgeEntry(state, step.response).rawValue == step.verdict,
                        "\(label): verdict")

                let before = state.draw
                state = try SpeedRun.answerRun(state, step.response, step.now)
                #expect((state.draw != before) == step.advanced, "\(label): advanced")
                Self.check(state, step.state, label)
            }

            let result = SpeedRun.runResult(state)
            #expect(result.correct == vector.result.correct, "\(vector.name): result")
            #expect(result.mode.key == vector.result.mode.mode?.key, "\(vector.name): result mode")
        }
    }

    @Test("every mode is played, so every spec is generated from")
    func everyModePlayed() {
        let played = Set(
            Self.corpus.runs
                .filter { $0.name.hasPrefix("mode:") }
                .map { String($0.name.dropFirst("mode:".count)) })
        #expect(played == Set(Modes.all.map(\.key)))
    }

    @Test("judgeEntry grades as it is typed")
    func judgeMatchesOracle() throws {
        #expect(!Self.corpus.judge.isEmpty)
        for vector in Self.corpus.judge {
            guard let mode = vector.mode.mode else { continue }
            let state = try SpeedRun.startRun(
                mode: mode, seed: vector.seed, startedAt: 0)
            #expect(state.current.answer.stringValue == vector.answer, "\(vector.name): answer")

            for entry in vector.entries {
                #expect(SpeedRun.judgeEntry(state, entry.entry).rawValue == entry.verdict,
                        "\(vector.name): \"\(entry.entry)\"")
            }
        }
    }

    @Test("a wrong answer changes nothing at all")
    func wrongAnswersDoNotAdvance() throws {
        let vector = Self.corpus.runs.first { $0.name == "wrong answers do not advance" }!
        let mode = vector.mode.mode!
        var state = try SpeedRun.startRun(
            mode: mode, seed: vector.seed, startedAt: vector.startedAt)

        let prompt = state.current.prompt
        let draw = state.draw
        state = try SpeedRun.answerRun(state, "999999", vector.startedAt + 1000)
        #expect(state.current.prompt == prompt)
        #expect(state.draw == draw)
        #expect(state.correct == 0)
    }

    // MARK: - The clock

    @Test("the clock, the buzzer and the pulse agree")
    func clockMatchesOracle() throws {
        for vector in Self.corpus.clock {
            let state = try SpeedRun.startRun(
                mode: .graded(.add, .easy), seed: "clock", startedAt: 1_700_000_000_000)
            #expect(SpeedRun.remainingMs(state, vector.now) == vector.remaining,
                    "elapsed \(vector.elapsed): remaining")
            #expect(SpeedRun.isOver(state, vector.now) == vector.isOver,
                    "elapsed \(vector.elapsed): isOver")
        }
    }

    @Test("an answer exactly on the buzzer still counts")
    func buzzerBoundary() throws {
        // `isOver` is strictly greater, so the last millisecond is still play.
        var state = try SpeedRun.startRun(mode: .graded(.add, .easy), seed: "b", startedAt: 0)
        #expect(SpeedRun.isOver(state, SpeedRun.runMs) == false)
        #expect(SpeedRun.isOver(state, SpeedRun.runMs + 1) == true)

        let answer = state.current.answer.stringValue
        state = try SpeedRun.answerRun(state, answer, SpeedRun.runMs)
        #expect(state.correct == 1, "an answer on the last millisecond counts")

        let after = try SpeedRun.answerRun(
            state, state.current.answer.stringValue, SpeedRun.runMs + 1)
        #expect(after.correct == 1, "an answer after the buzzer does not")
    }

    @Test("pulseFor steps at 30s, 15s and 5s")
    func pulsesMatchOracle() {
        for vector in Self.corpus.pulses {
            #expect(SpeedRun.pulseFor(vector.remaining).rawValue == vector.pulse,
                    "\(vector.remaining)")
        }
    }

    // MARK: - Records

    @Test("a first run is not a record")
    func recordsMatchOracle() {
        #expect(!Self.corpus.records.isEmpty)
        for vector in Self.corpus.records {
            #expect(
                SpeedRecords.isRecord(previousBest: vector.previousBest, score: vector.score)
                    == vector.isRecord,
                "best \(String(describing: vector.previousBest)) score \(vector.score)")
            #expect(
                SpeedRecords.resultTone(previousBest: vector.previousBest, score: vector.score)
                    .rawValue == vector.tone,
                "best \(String(describing: vector.previousBest)) score \(vector.score): tone")
        }
    }

    // MARK: - Constants

    @Test("the ported constants match the TypeScript")
    func constantsMatchOracle() {
        let c = Self.corpus.constants
        #expect(SpeedRun.runMs == c.SPEED_RUN_MS)
        #expect(SpeedRun.countdownMs == c.COUNTDOWN_MS)
        #expect(Modes.subject == c.SPEED_RUN_SUBJECT)
        #expect(Difficulty.allCases.map(\.rawValue) == c.DIFFICULTIES)
        #expect(Operation.allCases.map(\.rawValue) == c.OPERATIONS)
        #expect(Modes.tables == c.TABLES)
        #expect(Modes.singleTables == c.SINGLE_TABLES)
        #expect(Modes.tableBundles.map(\.key) == c.TABLE_BUNDLES)
    }

    @Test("ten is a table but not a mode, and stays in all")
    func tenIsNotAMode() {
        // Multiplying by ten is a place-value rule rather than a fact to
        // recall, so it is not a mode of its own — but `all` means all of them
        // and would be lying otherwise.
        #expect(Modes.singleTables.contains(10) == false)
        #expect(Modes.tables.contains(10))
        #expect(TableChoice.all.tables.contains(10))
        #expect(Modes.parseMode("multiply.10") == nil)
    }
}
