import Foundation

/// Question generation, ported from `src/lib/templates/generate.ts`.
///
/// This turns a template into a question a child sees. It is downstream of
/// `Rng` and `Expr` and it consumes both in a fixed order, which is the thing
/// to be careful about: the draws are a *sequence*, so a divergence that looks
/// local — one extra `next()`, one bound rounded the other way — reshuffles
/// every value after it and the question stops matching the web app's.
///
/// `GenerateTests` checks it against vectors generated by running the real
/// TypeScript, including all 378 figure-free shipped templates drawn three
/// times each.
///
/// A template carrying a figure draws it from the same scope and the same
/// `Rng`, between the answer and the choices — see `generate`.

/// How many times to redraw before giving up on a template's constraints.
private let maxAttempts = 200

public enum GenerateError: Error, CustomStringConvertible, Equatable {
    case notANumber(label: String, got: String)
    case emptyRange(name: String, min: Double, max: Double)
    case noValuesToPick(name: String)
    case weightCountMismatch(name: String, weights: Int, values: Int)
    case constraintsUnsatisfied(label: String, constraints: [String])
    case notEnoughChoices(got: Int, want: Int)

    public var description: String {
        switch self {
        case .notANumber(let label, let got):
            return "\(label) must evaluate to a number, got \(got)"
        case .emptyRange(let name, let min, let max):
            return "Variable \(name) has an empty range [\(JSNumber.toString(min)), \(JSNumber.toString(max))]"
        case .noValuesToPick(let name):
            return "Variable \(name) has no values to pick from"
        case .weightCountMismatch(let name, let weights, let values):
            return "Variable \(name) has \(weights) weights for \(values) values"
        case .constraintsUnsatisfied(let label, let constraints):
            return "Template \(label) failed to satisfy its constraints after "
                + "\(maxAttempts) attempts: [\(constraints.joined(separator: ", "))]"
        case .notEnoughChoices(let got, let want):
            return "Template could not produce \(want) distinct choices (got \(got)); "
                + "add more distractors or a jitter range"
        }
    }
}

/// Evaluate an expression that must produce a number.
///
/// NaN is rejected alongside non-numbers, exactly as the TypeScript's
/// `Number.isNaN` check does — a NaN bound would otherwise make every
/// comparison below false and yield an empty range with no explanation.
private func num(_ expr: Expr, _ scope: Scope, _ label: String) throws -> Double {
    let value = try evaluate(expr, scope)
    guard case .number(let n) = value, !n.isNaN else {
        // `JSON.stringify` of a string quotes it; of a boolean it does not.
        let got: String
        switch value {
        case .string(let s): got = jsonQuote(s)
        default: got = value.stringValue
        }
        throw GenerateError.notANumber(label: label, got: got)
    }
    return n
}

/// Draw one variable.
///
/// Every branch consumes a precise number of RNG draws, and the count differs
/// between branches — a weighted `pick` takes one `next()` where an unweighted
/// one takes an `int()`. That is why this is written against the JavaScript's
/// control flow rather than restructured.
private func bindVar(_ spec: VarSpec, _ scope: Scope, _ rng: inout Rng) throws -> Value {
    switch spec {
    case .int(let name, let minExpr, let maxExpr, let step):
        // `ceil` on the low bound and `floor` on the high one, so a fractional
        // bound narrows the range rather than widening it.
        let min = (try num(minExpr, scope, "\(name).min")).rounded(.up)
        let max = (try num(maxExpr, scope, "\(name).max")).rounded(.down)
        guard max >= min else {
            throw GenerateError.emptyRange(name: name, min: min, max: max)
        }
        // `> 1`, matching the JavaScript. A `step` of exactly 1 takes the
        // plain branch below, and provably cannot differ: `min + int(0, max-min) * 1`
        // and `int(min, max)` are the same arithmetic on the same single draw.
        // So no vector distinguishes `> 1` from `> 0` either - it is written
        // this way to match the source, not because a test demands it.
        if let step, step > 1 {
            // The top of the draw is the number of whole steps that fit, so a
            // step that does not divide the range evenly cannot reach `max`.
            let steps = ((max - min) / step).rounded(.down)
            return .number(min + Double(rng.int(0, Int(steps))) * step)
        }
        return .number(Double(rng.int(Int(min), Int(max))))

    case .number(let name, let minExpr, let maxExpr, let decimals):
        let min = try num(minExpr, scope, "\(name).min")
        let max = try num(maxExpr, scope, "\(name).max")
        guard max >= min else {
            throw GenerateError.emptyRange(name: name, min: min, max: max)
        }
        let places = decimals ?? 2
        let raw = min + rng.next() * (max - min)
        let factor = Foundation.pow(10.0, Double(places))
        // `JSNumber.round`, not Swift's `rounded()`: JavaScript breaks ties
        // toward +Infinity, so `round(-2.5)` is `-2` and not `-3`. A negative
        // range is where the two disagree.
        return .number(JSNumber.round(raw * factor) / factor)

    case .pick(let name, let from, let weights):
        guard !from.isEmpty else {
            throw GenerateError.noValuesToPick(name: name)
        }
        guard let weights else {
            return from[rng.int(0, from.count - 1)].value
        }
        guard weights.count == from.count else {
            throw GenerateError.weightCountMismatch(
                name: name, weights: weights.count, values: from.count
            )
        }
        let total = weights.reduce(0, +)
        // One `next()` here, where the unweighted branch spends an `int()`.
        var roll = rng.next() * total
        for i in from.indices {
            roll -= weights[i]
            // `<=`, matching the JavaScript. No vector can prove this against
            // `<`: they differ only when `roll` lands exactly on a cumulative
            // boundary, which needs `next()` to return a specific one of 2^32
            // values. It is written the JS way because it is a port, not
            // because a test caught it.
            if roll <= 0 { return from[i].value }
        }
        // Reached only through floating-point drift, when the weights do not
        // quite sum to `total`. The JavaScript falls back the same way.
        return from[from.count - 1].value

    case .expr(_, let expr):
        return try evaluate(expr, scope)
    }
}

/// One attempt at binding every variable. Returns nil if a constraint fails.
///
/// A rejected attempt still consumed its draws, and the next attempt carries on
/// from where it left off rather than resetting — which is why a template with
/// a tight constraint produces different values from one without.
private func tryBind(_ spec: QuestionSpec, _ rng: inout Rng) throws -> Scope? {
    var scope: Scope = [:]

    for varSpec in spec.vars {
        scope[varSpec.name] = try bindVar(varSpec, scope, &rng)
    }

    for constraint in spec.constraints ?? [] {
        if try !evaluateCondition(constraint, scope) { return nil }
    }

    return scope
}

/// Replace `{expression}` holes with their evaluated values.
///
/// The holes take arbitrary expressions, not just variable names, and the
/// result goes through JavaScript's `String()` — so a whole-number double
/// renders as `"2"` and not `"2.0"`. This text reaches a child, so that
/// distinction is the whole point.
public func renderTemplateString(_ text: String, _ scope: Scope) throws -> String {
    var out = ""
    var rest = Substring(text)

    while let open = rest.firstIndex(of: "{") {
        // `[^{}]+` — a hole holds no braces of its own, so an unmatched `{`
        // is literal text rather than the start of anything.
        let afterOpen = rest.index(after: open)
        guard let close = rest[afterOpen...].firstIndex(where: { $0 == "}" || $0 == "{" }),
              rest[close] == "}",
              close > afterOpen
        else {
            out += rest[...open]
            rest = rest[afterOpen...]
            continue
        }

        out += rest[rest.startIndex..<open]
        out += try evaluate(String(rest[afterOpen..<close]), scope).stringValue
        rest = rest[rest.index(after: close)...]
    }

    return out + rest
}

/// Build the options for a multiple-choice question.
///
/// The answer goes in first and the list is shuffled at the end, so the
/// shuffle is what hides it. Everything between is de-duplication by rendered
/// string: two expressions that produce the same text are one option, because
/// two identical buttons is a question with a wrong number of answers.
private func buildChoices(
    _ spec: ChoiceSpec,
    _ answer: Answer,
    _ scope: Scope,
    _ rng: inout Rng
) throws -> [Answer] {
    // Clamped rather than rejected: validation is the gate for authoring
    // mistakes, and this runs mid-session with a child waiting. Four options
    // that include the answer beat a thrown error.
    let count = Swift.min(spec.count, maxChoices)

    var options: [Answer] = [answer]
    var seen: Set<String> = [answer.stringValue]

    func add(_ value: Value) {
        // Booleans are dropped: a true/false answer renders its own buttons,
        // so a boolean among the options is an authoring mistake, not a choice.
        if case .boolean = value { return }
        let key = value.stringValue
        if seen.contains(key) { return }
        seen.insert(key)
        options.append(Answer(value))
    }

    for expr in spec.distractors ?? [] {
        if options.count >= count { break }
        add(try evaluate(expr, scope))
    }

    // Top up with jittered values when the authored distractors collide or run
    // out. Only numbers can be jittered — there is no "nearby" string.
    if options.count < count, let jitter = spec.jitter, case .number(let base) = answer {
        let min = try num(jitter.min, scope, "jitter.min")
        let max = try num(jitter.max, scope, "jitter.max")
        var guardCount = 0
        while options.count < count && guardCount < 100 {
            // Two draws per iteration, in this order: the offset, then the
            // sign. Swapping them silently changes every option.
            let offset = Double(rng.int(Int(min), Int(max)))
            let sign: Double = rng.next() < 0.5 ? -1 : 1
            add(.number(base + offset * sign))
            guardCount += 1
        }
    }

    guard options.count >= count else {
        throw GenerateError.notEnoughChoices(got: options.count, want: count)
    }

    // Fisher-Yates so the answer is not always first.
    var i = options.count - 1
    while i > 0 {
        let j = rng.int(0, i)
        options.swapAt(i, j)
        i -= 1
    }
    return options
}

/// Expand a spec into a question.
///
/// Nothing here throws on an authoring mistake that has a playable reading: a
/// disagreement between `answerType` and the actual answer degrades to
/// something a child can answer, because this runs mid-session. Validation is
/// where such a mistake is reported.
public func generate(
    _ spec: QuestionSpec,
    _ rng: inout Rng,
    label: String = "spec"
) throws -> GeneratedQuestion {
    var scope: Scope?
    var attempt = 0
    while attempt < maxAttempts && scope == nil {
        scope = try tryBind(spec, &rng)
        attempt += 1
    }

    guard let scope else {
        throw GenerateError.constraintsUnsatisfied(
            label: label, constraints: spec.constraints ?? []
        )
    }

    let answerValue = try evaluate(spec.answer, scope)

    // Built here, between the answer and the choices, because that is where it
    // sits in the RNG sequence: a figure drawn earlier or later would shift
    // every draw after it and change the question's own options.
    //
    // `buildFigure` is total by construction — an unknown shape or an unbound
    // parameter degrades to something drawable rather than throwing, exactly
    // like the rest of this function — so there is nothing here to guard.
    // Drawn from the same scope and the same `rng` the rest of the question
    // uses, which is what makes a figure reproduce from its seed.
    let figure = spec.figure.map { buildFigure($0, scope, &rng) }

    // A boolean answer is a true/false question whatever the spec declared:
    // its two options are implied, so any `choices` are meaningless and are
    // dropped.
    let isBoolean: Bool
    if case .boolean = answerValue { isBoolean = true } else { isBoolean = false }

    let answerType: AnswerType
    if isBoolean {
        answerType = .boolean
    } else if let declared = spec.answerType {
        answerType = declared
    } else if case .number = answerValue {
        answerType = .number
    } else {
        answerType = .text
    }

    let answer = Answer(answerValue)

    var choices: [Answer]?
    if let choiceSpec = spec.choices, !isBoolean {
        choices = try buildChoices(choiceSpec, answer, scope, &rng)
    }

    return GeneratedQuestion(
        prompt: try renderTemplateString(spec.prompt, scope),
        answer: answer,
        answerType: answerType,
        choices: choices,
        hint: try spec.hint.map { try renderTemplateString($0, scope) },
        vars: scope.mapValues(Answer.init),
        figure: figure
    )
}

/// A generated question, placed in a course.
///
/// Every field the engine needs to make one lives on the spec; these four say
/// who was asked, and are carried straight through.
public func generateQuestion(
    _ template: QuestionTemplate,
    _ rng: inout Rng
) throws -> Question {
    Question(
        templateId: template.id,
        subject: template.subject,
        topic: template.topic,
        level: template.level,
        question: try generate(template.spec, &rng, label: template.id)
    )
}
